### ISSUE TITLE
when I install tendermint, do a tendermint init, and then launch glogchain, I get

### ISSUE THREAD

**Issue by faddat** [baabeetaa/glogchain#2]
**Tendermint Output**

```
[faddat@arch-anywhere][~/go/src/github.com/tendermint/tendermint]% tendermint node
NOTE[11-21|19:47:15] Loaded PrivValidator                     module=types file=/home/faddat/.tendermint/priv_validator.json privValidator="PrivValidator{36BD9963BDAD663FD8938683758AB33B2D7D1283 LH:0, LR:0, LS:0}"
WARN[11-21|19:47:15] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:18] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:21] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:24] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:27] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:30] tmsp.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=tmspcli
WARN[11-21|19:47:33] Stopping tmsp.socketClient for error: Unexpected result type <nil> when nothing expected module=tmspcli
WARN[11-21|19:47:33] Stopping tmsp.socketClient for error: Unexpected result type <nil> when nothing expected module=tmspcli
WARN[11-21|19:47:33] Stopping tmsp.socketClient for error: Unexpected result type <nil> when nothing expected module=tmspcli
panic: Paniced on a Crisis: listen tcp 0.0.0.0:46656: bind: address already in use

goroutine 1 [running]:
panic(0x95f080, 0xc42011e2c0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.PanicCrisis(0x9a1a60, 0xc42005d180)
	/home/faddat/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/errors.go:33 +0xe0
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-p2p.NewDefaultListener(0xc420163380, 0x3, 0xc420163386, 0xd, 0xc420163300, 0xd, 0xc42011ea30)
	/home/faddat/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-p2p/listener.go:66 +0x81f
github.com/tendermint/tendermint/node.RunNode(0xe220a0, 0xc420163580)
	/home/faddat/go/src/github.com/tendermint/tendermint/node/node.go:346 +0x60c
main.main()
	/home/faddat/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x373
```

**glogchain output**

```
2016/11/21 19:47:33 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2016/11/21 19:47:33 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
2016/11/21 19:47:33 transport: http2Server.HandleStreams failed to receive the preface from client: EOF
^Ccaptured interrupt, exiting...
```

**Comment by faddat** [comment]
Solved in a temporary fashion by first launching glogchain then tendermint.  Go figure.

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/20484257/f0965738-b028-11e6-944e-b01113564c24.png)
